#!/usr/bin/env bash

curl -o install-openshift.sh https://raw.githubusercontent.com/cmcornejocrespo/installcentos/master/install-openshift.sh
chmod +x install-openshift.sh
time DOMAIN=openshift USERNAME=developer PASSWORD=any ./install-openshift.sh

cd /vagrant/demo-ci-cd
chmod +x demo-*
./demo-bootstrap