#!/usr/bin/env bash
docker pull openshiftdemos/gogs:0.11.29 && \
docker pull openshiftdemos/sonarqube:6.7 && \
docker pull sonatype/nexus3:3.6.1 && \
docker pull registry.access.redhat.com/openshift3/jenkins-2-rhel7 && \
docker pull registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7 && \
docker pull registry.access.redhat.com/jboss-eap-7/eap70-openshift