#!/usr/bin/env bash
docker pull openshiftdemos/gogs:0.11.34 && \
docker pull registry.centos.org/rhsyseng/sonarqube:latest && \
docker pull sonatype/nexus3:3.7.1 && \
docker pull registry.access.redhat.com/openshift3/jenkins-2-rhel7 && \
docker pull registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7 && \
docker pull registry.access.redhat.com/jboss-eap-7/eap70-openshift