#!/usr/bin/env bash

/usr/local/bin/oc login -u system:admin
# Make sure latest Jenkins image is installed
/usr/local/bin/oc import-image jenkins:v3.7 --from="registry.access.redhat.com/openshift3/jenkins-2-rhel7" --confirm -n openshift
/usr/local/bin/oc tag jenkins:v3.7 jenkins:latest -n openshift

# Manage policy on the cluster
/usr/local/bin/oc adm policy add-role-to-user admin system -n dev
/usr/local/bin/oc adm policy add-role-to-user admin system -n stage
/usr/local/bin/oc adm policy add-role-to-user admin system -n cicd

# Update the annotations on namespace resources
/usr/local/bin/oc annotate --overwrite namespace dev demo=openshift-cd
/usr/local/bin/oc annotate --overwrite namespace stage demo=openshift-cd
/usr/local/bin/oc annotate --overwrite namespace cicd  demo=openshift-cd

/usr/local/bin/oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.10/jboss-image-streams.json -n openshift