#!/usr/bin/env bash

oc login -u developer -p any
# Create Projects
echo "Creating DEV namespace ..."
oc new-project dev --display-name="Dev Environment" && \
echo "Creating STAGE namespace ..."
oc new-project stage --display-name="Stage environment" && \
echo "Creating CI/CD namespace ..."
oc new-project cicd --display-name="CI/CD Management"

# Give the Jenkins Pod [service account](https://docs.openshift.org/latest/admin_guide/service_accounts.html)
# rights to do API calls to OpenShift.
echo "Adding roles to admin user ..."
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n dev
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n stage
